name: Validate fix

on:
  workflow_dispatch:
  push:
    branches: ["aves-fix"]
  pull_request:
    branches: ["develop"]
    types: [opened, synchronize, reopened, ready_for_review]

permissions: read-all

jobs:
  analyze_flutter:
    name: Flutter analysis and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Flutter packages
        run: ./flutterw pub get

      - name: Generate app localizations
        run: ./flutterw gen-l10n

      - name: Static analysis
        run: ./flutterw analyze

      - name: Unit tests
        run: ./flutterw test

  build_apk:
    name: Build profile APK
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: "21"

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Apply Play flavor
        run: scripts/apply_flavor_play.sh

      - name: Build profile APK
        run: ./flutterw build apk --profile -t lib/main_play.dart --flavor play

      - name: Upload profile APK
        uses: actions/upload-artifact@v4
        with:
          name: aves-play-profile-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
